
import { Job, StudentProfile, ShiftType, WorkType } from './types';

export const MOCK_JOBS: Job[] = [
  {
    id: '1',
    title: 'Serveringspersonal kvällspass',
    company: 'Restaurang Havet',
    employerId: 'emp1',
    city: 'Stockholm',
    hourlyRate: 145,
    startTime: 'Ikväll kl 18:00',
    duration: '5 timmar',
    workType: WorkType.Physical,
    shiftType: ShiftType.Evening,
    requirements: ['Servicevana', 'Stressålig'],
    employerRequirements: ['Svart skjorta/blus', 'Skall kunna bära 3 tallrikar', 'Flytande svenska'],
    description: 'Vi behöver extra förstärkning ikväll.',
    workingConditions: 'Varmt arbetsklimat, högt tempo, mat ingår.',
    isQuickShift: true,
    isRecurring: false,
    isGroupJob: true,
    travelReimbursement: false,
  },
  {
    id: '2',
    title: 'Lagerarbetare förmiddag',
    company: 'Logistik AB',
    employerId: 'emp2',
    city: 'Göteborg',
    hourlyRate: 138,
    startTime: 'Imorgon kl 08:00',
    duration: '6 timmar',
    workType: WorkType.Physical,
    shiftType: ShiftType.Morning,
    requirements: ['Fysiskt stark'],
    employerRequirements: ['Skyddsskor (finns att låna)', 'Körkort B är meriterande', 'Punktlighet'],
    description: 'Packning och sortering.',
    workingConditions: 'Kyligt lager, kräver tunga lyft, skyddskläder tillhandahålls.',
    isQuickShift: false,
    isRecurring: true,
    isGroupJob: false,
    travelReimbursement: true,
  },
  {
    id: '3',
    title: 'Butikssäljare Knalleland',
    company: 'Knalleland Livs i Borås',
    employerId: 'emp3',
    city: 'Borås',
    hourlyRate: 142,
    startTime: 'Imorgon kl 12:00',
    duration: '4 timmar',
    workType: WorkType.Physical,
    shiftType: ShiftType.Day,
    requirements: ['Kassavana', 'Kundfokus'],
    employerRequirements: ['Flytande svenska', 'Ålder 18+ år', 'Flexibilitet'],
    description: 'Extra hjälp i kassan och vid varupåfyllning under helgruschen i Knalleland.',
    workingConditions: 'Glatt team, varierat tempo, schyssta villkor.',
    isQuickShift: true,
    isRecurring: false,
    isGroupJob: false,
    travelReimbursement: false,
  }
];

export const MOCK_STUDENT: StudentProfile = {
  id: 'std123',
  name: 'Erik Andersson',
  age: 22,
  city: 'Stockholm',
  education: 'Civilekonom, Stockholms Universitet',
  availability: [ShiftType.Evening, ShiftType.Weekend],
  blockedDates: [],
  experienceTags: ['Service', 'Administration'],
  workPreference: WorkType.Hybrid,
  verified: true,
  rating: 4.8,
  jobsCompleted: 12,
  level: 3,
  badges: ['Punktlig', 'Snabba Svar', 'Topp-rankad'],
  reliabilityScore: 98,
  totalEarned: 15400,
  responseTime: '15 min',
  favoriteJobs: [],
};
